version: '3.1'

services:
  logr:
    build:
      context: "."
      args:
        app_apikey: ${APP_APIKEY}
        output: "file" #"file" or "database"
        
        #if output: "database"
        database_type: "mongodb" #mariadb planned but not yet implemented

        #if database_type: "mongodb"
        mongodb_connection_string: ${MONGODB_CONNECTION_STRING}
    ports:
      - 32032:32032
    
    volumes: #required if output: "file"
      - logr:/logr

volumes:
  logr:
    external: true
